INSERT INTO ConfigurationField(Field, TargetTable, Type, InitialValue, Description) VALUES
    ('Artshow_ArtAuction', 'Artshow_Configuration', 'boolean', 1, 'There an art auction.'),
    ('Artshow_BidTagBarcode', 'Artshow_Configuration', 'boolean', 1, 'Do bid tags have a barcode.'),
    ('Artshow_BidTag2DBarcode', 'Artshow_Configuration', 'boolean', 1, 'Do bid tags have a 2D barcode.'),
    ('Artshow_BidTagFont', 'Artshow_Configuration', 'text', 'times', 'Font on the bid tags.'),
    ('Artshow_BidTagFontSize', 'Artshow_Configuration', 'integer', 9, 'Font size on the bid tags.'),
    ('Artshow_BidTagMargins', 'Artshow_Configuration', 'integer', 5, 'Margins around the edge of the bid tag sheet.'),
    ('Artshow_BidTagPaperOrientation', 'Artshow_Configuration', 'select', 'LANDSCAPE', 'Paper orientation for printing bid tags.'),
    ('Artshow_BidTagPaperSize', 'Artshow_Configuration', 'select', 'LETTER', 'Paper size for printing bid tags.'),
    ('Artshow_BidTagTitle', 'Artshow_Configuration', 'text', '', 'Title on each bid tag.'),
    ('Artshow_BidTagInfo1', 'Artshow_Configuration', 'text', '', 'Info 1 block on each bid tag.'),
    ('Artshow_BidTagInfo2', 'Artshow_Configuration', 'text', '', 'Info 2 block on each bid tag.'),
    ('Artshow_BidTagsPerRow', 'Artshow_Configuration', 'integer', 3, 'Number of bid tags per printed row.'),
    ('Artshow_BidsUntilAuction', 'Artshow_Configuration', 'integer', 3, 'How many bids until a piece goes to auction.'),
    ('Artshow_DefaultType', 'Artshow_Configuration', 'select', 'Normal', 'Default type when entering types.'),
    ('Artshow_DisplayComission', 'Artshow_Configuration', 'integer', 10, 'Commission for display art in percent.'),
    ('Artshow_DisplayLimit', 'Artshow_Configuration', 'integer', 20, 'Limit to number of display pieces.'),
    ('Artshow_HangingFee', 'Artshow_Configuration', 'text', 1, 'Display art hanging fee.'),
    ('Artshow_NFSHangingFee', 'Artshow_Configuration', 'text', 2, 'Not For Sale display art hanging fee.'),
    ('Artshow_PrintShop', 'Artshow_Configuration', 'boolean', 1, 'There an art print shop.'),
    ('Artshow_PrintShopComission', 'Artshow_Configuration', 'integer', 10, 'Commission for print shop art in percent.')
