<?php

// Hotel Room Allocations

$AllocHotels = [
  "Doubletree By Hilton" => [
    "Location" => "7800 Normandale Blvd, Bloomington MN 55014",
    "Phone"    => "952-835-7800",
    "Prefix"   => "DT",
    "Contact"  => "Sarah Bivans",
    "Email"    => "tskeeley@gmail.com",
//    "Email"    => "sarah.bivans@hilton.com",
  ],
];

$AllocRoomTypes = [
  "Double",
  "King",
  "HC",
  "Suite",
];

$AllocRooms = [
  "DT" => [
    "0102" => [
      "Type" => "King",
      "Reserve" => "Parties",
    ],
    "0103" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0104" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0105" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0106" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0107" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0108" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0109" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0110" => [
      "Type" => "King",
      "Reserve" => "Parties",
    ],
    "0114" => [
      "Type" => "Double",
      "Reserve" => "CVGNeeds",
    ],
    "0115" => [
      "Type" => "Suite",
      "Reserve" => "CVGNeeds",
    ],
    "0116" => [
      "Type" => "King",
      "Reserve" => "CVGNeeds",
    ],
    "0117" => [
      "Type" => "Double",
      "Reserve" => "CVGNeeds",
    ],
    "0118" => [
      "Type" => "Suite",
      "Reserve" => "CVGNeeds",
    ],
    "0119" => [
      "Type" => "Double",
      "Reserve" => "CVGNeeds",
    ],
    "0123" => [
      "Type" => "King",
      "Reserve" => "Parties",
    ],
    "0124" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0125" => [
      "Type" => "King",
      "Reserve" => "Parties",
    ],
    "0126" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0127" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0128" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0129" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0130" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0131" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0201" => [
      "Type" => "King",
      "Reserve" => "Parties",
    ],
    "0202" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0203" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0204" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0205" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0206" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0207" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0208" => [
      "Type" => "King",
      "Reserve" => "Parties",
    ],
    "0209" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0210" => [
      "Type" => "King",
      "Reserve" => "Parties",
    ],
    "0212" => [
      "Type" => "King",
      "Reserve" => "CVGNeeds",
    ],
    "0213" => [
      "Type" => "Double",
      "Reserve" => "CVGNeeds",
    ],
    "0214" => [
      "Type" => "King",
      "Reserve" => "CVGNeeds",
    ],
    "0215" => [
      "Type" => "Suite",
      "Reserve" => "CVGNeeds",
    ],
    "0216" => [
      "Type" => "King",
      "Reserve" => "CVGNeeds",
    ],
    "0217" => [
      "Type" => "Double",
      "Reserve" => "CVGNeeds",
    ],
    "0218" => [
      "Type" => "Suite",
      "Reserve" => "CVGNeeds",
    ],
    "0219" => [
      "Type" => "Double",
      "Reserve" => "CVGNeeds",
    ],
    "0220" => [
      "Type" => "King",
      "Reserve" => "CVGNeeds",
    ],
    "0222" => [
      "Type" => "King",
      "Reserve" => "CVGNeeds",
    ],
    "0223" => [
      "Type" => "King",
      "Reserve" => "Parties",
    ],
    "0224" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0225" => [
      "Type" => "King",
      "Reserve" => "Parties",
    ],
    "0226" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0227" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0228" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0229" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0230" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0231" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0232" => [
      "Type" => "King",
      "Reserve" => "Parties",
    ],
    "0401" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0402" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0403" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0404" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0405" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0406" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0407" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0408" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0409" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0410" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "0411" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0412" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0413" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0414" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0415" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0416" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0417" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0418" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0419" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0420" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0422" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0451" => [
      "Type" => "King",
      "Reserve" => "CVGSpecial",
    ],
    "0452" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "0453" => [
      "Type" => "Double",
      "Reserve" => "CVGSpecial",
    ],
    "0454" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0455" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0456" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "0457" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0458" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "0459" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0460" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0461" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0462" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0463" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0464" => [
      "Type" => "Double",
      "Reserve" => "CVGSpecial",
    ],
    "0465" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0466" => [
      "Type" => "Double",
      "Reserve" => "CVGSpecial",
    ],
    "0467" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0468" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0469" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0470" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0471" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0472" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0473" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0474" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0475" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0476" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0477" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0478" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0479" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0480" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0481" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0482" => [
      "Type" => "Suite",
      "Reserve" => "Board",
    ],
    "0483" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0501" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0502" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0503" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0504" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0505" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0506" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0507" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0508" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0509" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0510" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0511" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0512" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0513" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0514" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0515" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0516" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0517" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0518" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0519" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0520" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0522" => [
      "Type" => "Double",
      "Reserve" => "ADO",
    ],
    "0551" => [
      "Type" => "Double",
      "Reserve" => "CVGSpecial",
    ],
    "0552" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0553" => [
      "Type" => "Double",
      "Reserve" => "CVGSpecial",
    ],
    "0554" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0555" => [
      "Type" => "Double",
      "Reserve" => "InvParticipant",
    ],
    "0556" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "0557" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0558" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "0559" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0560" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0561" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0562" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0563" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0564" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0565" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0566" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0567" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0568" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0569" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0570" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0571" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0572" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0573" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0574" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0575" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0576" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0577" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0578" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0579" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0580" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0581" => [
      "Type" => "King",
      "Reserve" => "CVGSpecial",
    ],
    "0582" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "0583" => [
      "Type" => "Double",
      "Reserve" => "CVGSpecial",
    ],
    "0584" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0601" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0602" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0603" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0604" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0605" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0606" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0607" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0608" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0609" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0610" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0611" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0612" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0613" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0614" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0615" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0616" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0617" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0618" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0619" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0620" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0622" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0651" => [
      "Type" => "Double",
      "Reserve" => "IWBlock",
    ],
    "0652" => [
      "Type" => "King",
      "Reserve" => "CVGSpecial",
    ],
    "0653" => [
      "Type" => "King",
      "Reserve" => "CVGSpecial",
    ],
    "0654" => [
      "Type" => "King",
      "Reserve" => "CVGSpecial",
    ],
    "0655" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0656" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "0657" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0658" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "0659" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0660" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0661" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0662" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0663" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0664" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0665" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0666" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0667" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0668" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0669" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0670" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0671" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0672" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0673" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0674" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0675" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0676" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0677" => [
      "Type" => "King",
      "Reserve" => "CVGSpecial",
    ],
    "0678" => [
      "Type" => "King",
      "Reserve" => "Board",
    ],
    "0679" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0680" => [
      "Type" => "King",
      "Reserve" => "Board",
    ],
    "0681" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0682" => [
      "Type" => "Suite",
      "Reserve" => "Board",
    ],
    "0683" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "0701" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0702" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0703" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0704" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0705" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0706" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0707" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0708" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0709" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0710" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0711" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0712" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0713" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0714" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0715" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0716" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0717" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0718" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0719" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0720" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0722" => [
      "Type" => "Double",
      "Reserve" => "Parties",
    ],
    "0751" => [
      "Type" => "Double",
      "Reserve" => "Guests",
    ],
    "0753" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0755" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0756" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "0757" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0758" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "0759" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0760" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0761" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0762" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0763" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0764" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0765" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0766" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0767" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0768" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0769" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0770" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0771" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0772" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0773" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0774" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0775" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0776" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0777" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0778" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0779" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0780" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0781" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0782" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0783" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0784" => [
      "Type" => "King",
      "Reserve" => "Guests",
    ],
    "0801" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0802" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0803" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0804" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0805" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0806" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0807" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0808" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0809" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0810" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0811" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0812" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0813" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0814" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0815" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0816" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0817" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0818" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0819" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0820" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0822" => [
      "Type" => "Double",
      "Reserve" => "CVGSpecial",
    ],
    "0851" => [
      "Type" => "Double",
      "Reserve" => "TKBlock",
    ],
    "0852" => [
      "Type" => "Double",
      "Reserve" => "TKBlock",
    ],
    "0853" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0854" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0855" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0856" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "0857" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0858" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "0859" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0860" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0861" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0862" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0863" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0864" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0865" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0866" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0867" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0868" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0869" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0870" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0871" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0872" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0873" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0874" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0875" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0876" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0877" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0878" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0879" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0880" => [
      "Type" => "King",
      "Reserve" => "TKBlock",
    ],
    "0881" => [
      "Type" => "King",
      "Reserve" => "Board",
    ],
    "0882" => [
      "Type" => "Suite",
      "Reserve" => "Board",
    ],
    "0901" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "0902" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0903" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "0904" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0905" => [
      "Type" => "King",
      "Reserve" => "CVGSpecial",
    ],
    "0906" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0907" => [
      "Type" => "King",
      "Reserve" => "CVGSpecial",
    ],
    "0908" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0909" => [
      "Type" => "King",
      "Reserve" => "CVGSpecial",
    ],
    "0910" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0911" => [
      "Type" => "King",
      "Reserve" => "CVGSpecial",
    ],
    "0912" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0913" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "0914" => [
      "Type" => "Double",
      "Reserve" => "CVGSpecial",
    ],
    "0915" => [
      "Type" => "King",
      "Reserve" => "CVGSpecial",
    ],
    "0916" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "0917" => [
      "Type" => "King",
      "Reserve" => "CVGSpecial",
    ],
    "0918" => [
      "Type" => "Double",
      "Reserve" => "CVGSpecial",
    ],
    "0919" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "0920" => [
      "Type" => "Double",
      "Reserve" => "CVGSpecial",
    ],
    "0922" => [
      "Type" => "Double",
      "Reserve" => "CVGSpecial",
    ],
    "1001" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1002" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1003" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1004" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1005" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1006" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1007" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1008" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1009" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1010" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1011" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1012" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1013" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "1014" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1015" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1016" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1017" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "1018" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1019" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1020" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1022" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1101" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1102" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1103" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1104" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1105" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1106" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1107" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "1108" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1109" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1110" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1111" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1112" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1113" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1114" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1115" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1116" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1117" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1118" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1119" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1120" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1122" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1201" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1202" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1203" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1204" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1205" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1206" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1207" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "1208" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1209" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1210" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1211" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1212" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1213" => [
      "Type" => "King",
      "Reserve" => "IWBlock",
    ],
    "1214" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1215" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1216" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1217" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1218" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1219" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1220" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1222" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1401" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1402" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1403" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1404" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1405" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1406" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1407" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1408" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1409" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1410" => [
      "Type" => "Double",
      "Reserve" => "Pocket",
    ],
    "1411" => [
      "Type" => "King",
      "Reserve" => "Pocket",
    ],
    "1412" => [
      "Type" => "Double",
      "Reserve" => "Pocket",
    ],
    "1413" => [
      "Type" => "King",
      "Reserve" => "Pocket",
    ],
    "1414" => [
      "Type" => "Double",
      "Reserve" => "Pocket",
    ],
    "1415" => [
      "Type" => "King",
      "Reserve" => "Pocket",
    ],
    "1416" => [
      "Type" => "Double",
      "Reserve" => "Pocket",
    ],
    "1417" => [
      "Type" => "King",
      "Reserve" => "Pocket",
    ],
    "1418" => [
      "Type" => "Double",
      "Reserve" => "Pocket",
    ],
    "1419" => [
      "Type" => "King",
      "Reserve" => "Pocket",
    ],
    "1420" => [
      "Type" => "Double",
      "Reserve" => "InvParticipant",
    ],
    "1422" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1501" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1502" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1503" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1504" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1505" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1506" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1507" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1508" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1509" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1510" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1511" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1512" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1513" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1514" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1515" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1516" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1517" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1518" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1519" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "1520" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1522" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1601" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1602" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1603" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1604" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1605" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1606" => [
      "Type" => "Suite",
      "Reserve" => "IWBlock",
    ],
    "1607" => [
      "Type" => "King",
      "Reserve" => "Parties",
    ],
    "1609" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1610" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1611" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1612" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1613" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1614" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1615" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1616" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1617" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1618" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1619" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1620" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1622" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1701" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1702" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1703" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1704" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1705" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1706" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1707" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1708" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1709" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1710" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1711" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1712" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1713" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "1714" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1715" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1716" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1717" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1718" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1719" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1720" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1722" => [
      "Type" => "Double",
      "Reserve" => "",
    ],
    "1801" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1802" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1803" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1804" => [
      "Type" => "King",
      "Reserve" => "Board",
    ],
    "1805" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1806" => [
      "Type" => "Suite",
      "Reserve" => "Board",
    ],
    "1807" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1809" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1810" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "1811" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1812" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1813" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "1814" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1815" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1816" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1817" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1818" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1819" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1820" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1822" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1901" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1902" => [
      "Type" => "Double",
      "Reserve" => "InvParticipant",
    ],
    "1903" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1904" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1905" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1906" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1907" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1908" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1909" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1910" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1911" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1912" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1913" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1914" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1915" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "1916" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1917" => [
      "Type" => "King",
      "Reserve" => "Pocket",
    ],
    "1918" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1919" => [
      "Type" => "King",
      "Reserve" => "Pocket",
    ],
    "1920" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "1922" => [
      "Type" => "Double",
      "Reserve" => "InvParticipant",
    ],
    "2001" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2002" => [
      "Type" => "Suite",
      "Reserve" => "Board",
    ],
    "2003" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2005" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2006" => [
      "Type" => "Suite",
      "Reserve" => "Board",
    ],
    "2007" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2009" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2010" => [
      "Type" => "HC",
      "Reserve" => "ADA",
    ],
    "2011" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2012" => [
      "Type" => "Double",
      "Reserve" => "InvParticipant",
    ],
    "2013" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2014" => [
      "Type" => "Suite",
      "Reserve" => "CVGSpecial",
    ],
    "2015" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2017" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2019" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2020" => [
      "Type" => "Suite",
      "Reserve" => "CVGSpecial",
    ],
    "2022" => [
      "Type" => "Double",
      "Reserve" => "InvParticipant",
    ],
    "2101" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2102" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "2103" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2104" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2105" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2106" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2107" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2108" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2109" => [
      "Type" => "King",
      "Reserve" => "",
    ],
    "2110" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2111" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2112" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2113" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2114" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2115" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2116" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2117" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2118" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2119" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2120" => [
      "Type" => "King",
      "Reserve" => "InvParticipant",
    ],
    "2122" => [
      "Type" => "King",
      "Reserve" => "Department",
    ],
  ],
];

function totalAvailableRooms($hotel) {
  global $AllocRooms;
  foreach ($AllocRooms[$hotel] as $room) {
    if(empty($counts[$room['Type']])) {
      $counts[$room['Type']] = 1;
    } else {
      $counts[$room['Type']]++;
    }
    if(!empty($room['Reserve'])) {
      if(empty($counts[$room['Reserve']])) {
        $counts[$room['Reserve']] = 1;
      } else {
        $counts[$room['Reserve']]++;
      }
    }
  }
  $counts['Total'] = count($AllocRooms[$hotel]);
  return $counts;
}

?>
