<?php

// Hotel Room Allocations

$AllocHotels = [
  "Doubletree By Hilton" => [
    "Location" => "7800 Normandale Blvd, Bloomington MN 55014",
    "Phone"    => "952-835-7800",
    "Prefix"   => "DT",
    "Contact"  => "Sarah Bivans",
    "Email"    => "sarah.bivans@hilton.com",
  ],
];

$AllocRoomTypes = [
  "Double",
  "King",
  "HC",
  "Suite",
];

$AllocRooms = [
  "DT" => [
    "01" => [
      "02" => [
        "Type" => "King",
        "Reserve" => "Parties",
      ],
      "03" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "05" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "07" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "09" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "10" => [
        "Type" => "King",
        "Reserve" => "Parties",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "CVGNeeds",
      ],
      "15" => [
        "Type" => "Suite",
        "Reserve" => "CVGNeeds",
      ],
      "16" => [
        "Type" => "King",
        "Reserve" => "CVGNeeds",
      ],
      "17" => [
        "Type" => "Double",
        "Reserve" => "CVGNeeds",
      ],
      "18" => [
        "Type" => "Suite",
        "Reserve" => "CVGNeeds",
      ],
      "23" => [
        "Type" => "King",
        "Reserve" => "Parties",
      ],
      "24" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "25" => [
        "Type" => "King",
        "Reserve" => "Parties",
      ],
      "26" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "27" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "28" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "29" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "30" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "31" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
    ],
    "02" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "Parties",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "03" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "05" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "07" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "08" => [
        "Type" => "King",
        "Reserve" => "Parties",
      ],
      "09" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "10" => [
        "Type" => "King",
        "Reserve" => "Parties",
      ],
      "12" => [
        "Type" => "King",
        "Reserve" => "CVGNeeds",
      ],
      "13" => [
        "Type" => "Double",
        "Reserve" => "CVGNeeds",
      ],
      "14" => [
        "Type" => "King",
        "Reserve" => "CVGNeeds",
      ],
      "15" => [
        "Type" => "Suite",
        "Reserve" => "CVGNeeds",
      ],
      "16" => [
        "Type" => "King",
        "Reserve" => "CVGNeeds",
      ],
      "17" => [
        "Type" => "Double",
        "Reserve" => "CVGNeeds",
      ],
      "18" => [
        "Type" => "Suite",
        "Reserve" => "CVGNeeds",
      ],
      "19" => [
        "Type" => "Double",
        "Reserve" => "CVGNeeds",
      ],
      "20" => [
        "Type" => "King",
        "Reserve" => "CVGNeeds",
      ],
      "22" => [
        "Type" => "King",
        "Reserve" => "CVGNeeds",
      ],
      "23" => [
        "Type" => "King",
        "Reserve" => "Parties",
      ],
      "24" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "25" => [
        "Type" => "King",
        "Reserve" => "Parties",
      ],
      "26" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "27" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "28" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "29" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "30" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "31" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "32" => [
        "Type" => "King",
        "Reserve" => "Parties",
      ],
    ],
    "04" => [
      "01" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "03" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "05" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "07" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "09" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "10" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "11" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "13" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "15" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "17" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "19" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "51" => [
        "Type" => "King",
        "Reserve" => "CVGSpecial",
      ],
      "52" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "53" => [
        "Type" => "Double",
        "Reserve" => "CVGSpecial",
      ],
      "54" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "55" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "56" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "57" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "58" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "59" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "60" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "61" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "62" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
      "63" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "64" => [
        "Type" => "Double",
        "Reserve" => "CVGSpecial",
      ],
      "65" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "66" => [
        "Type" => "Double",
        "Reserve" => "CVGSpecial",
      ],
      "67" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "68" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "69" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "70" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "71" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
      "72" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "73" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
      "74" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "75" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
      "76" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "77" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
      "78" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "79" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "80" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "81" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
      "82" => [
        "Type" => "Suite",
        "Reserve" => "Board",
      ],
      "83" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
    ],
    "05" => [
      "01" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "03" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "05" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "07" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "09" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "10" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "11" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "13" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "15" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "17" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "19" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "ADO",
      ],
      "51" => [
        "Type" => "Double",
        "Reserve" => "CVGSpecial",
      ],
      "52" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
      "53" => [
        "Type" => "Double",
        "Reserve" => "CVGSpecial",
      ],
      "54" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "55" => [
        "Type" => "Double",
        "Reserve" => "InvParticipant",
      ],
      "56" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "57" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "58" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "59" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "60" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
      "61" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "62" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "63" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "64" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "65" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "66" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "67" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "68" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "69" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "70" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "71" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "72" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "73" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "74" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "75" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "76" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "77" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "78" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "79" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "80" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
      "81" => [
        "Type" => "King",
        "Reserve" => "CVGSpecial",
      ],
      "82" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "83" => [
        "Type" => "Double",
        "Reserve" => "CVGSpecial",
      ],
      "84" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
    ],
    "06" => [
      "01" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "03" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "05" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "07" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "09" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "10" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "11" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "13" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "15" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "17" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "19" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "51" => [
        "Type" => "Double",
        "Reserve" => "IWBlock",
      ],
      "52" => [
        "Type" => "King",
        "Reserve" => "CVGSpecial",
      ],
      "53" => [
        "Type" => "King",
        "Reserve" => "CVGSpecial",
      ],
      "54" => [
        "Type" => "King",
        "Reserve" => "CVGSpecial",
      ],
      "55" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "56" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "57" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "58" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "59" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "60" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "61" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "62" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "63" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "64" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "65" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "66" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "67" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "68" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "69" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "70" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "71" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "72" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "73" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "74" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "75" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "76" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "77" => [
        "Type" => "King",
        "Reserve" => "CVGSpecial",
      ],
      "78" => [
        "Type" => "King",
        "Reserve" => "Board",
      ],
      "79" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "80" => [
        "Type" => "King",
        "Reserve" => "Board",
      ],
      "81" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
      "82" => [
        "Type" => "Suite",
        "Reserve" => "Board",
      ],
      "83" => [
        "Type" => "King",
        "Reserve" => "IWBlock",
      ],
    ],
    "07" => [
      "01" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "03" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "05" => [
        "Type" => "Double",
        "Reserve" => "Parties",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "07" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "09" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "10" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "11" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "13" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "15" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "17" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "19" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "51" => [
        "Type" => "Double",
        "Reserve" => "Guests",
      ],
      "53" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "55" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "56" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "57" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "58" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "59" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "60" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "61" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "62" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "63" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "64" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "65" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "66" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "67" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "68" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "69" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "70" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "71" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "72" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "73" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "74" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "75" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "76" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "77" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "78" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "79" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "80" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "81" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "82" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "83" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
      "84" => [
        "Type" => "King",
        "Reserve" => "Guests",
      ],
    ],
    "08" => [
      "01" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "03" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "05" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "07" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "09" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "10" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "11" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "13" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "15" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "17" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "19" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "CVGSpecial",
      ],
      "51" => [
        "Type" => "Double",
        "Reserve" => "TKBlock",
      ],
      "52" => [
        "Type" => "Double",
        "Reserve" => "TKBlock",
      ],
      "53" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "54" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "55" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "56" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "57" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "58" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "59" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "60" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "61" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "62" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "63" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "64" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "65" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "66" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "67" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "68" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "69" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "70" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "71" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "72" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "73" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "74" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "75" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "76" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "77" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "78" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "79" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "80" => [
        "Type" => "King",
        "Reserve" => "TKBlock",
      ],
      "81" => [
        "Type" => "King",
        "Reserve" => "Board",
      ],
      "82" => [
        "Type" => "Suite",
        "Reserve" => "Board",
      ],
    ],
    "09" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "03" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "05" => [
        "Type" => "King",
        "Reserve" => "CVGSpecial",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "07" => [
        "Type" => "King",
        "Reserve" => "CVGSpecial",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "09" => [
        "Type" => "King",
        "Reserve" => "CVGSpecial",
      ],
      "10" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "11" => [
        "Type" => "King",
        "Reserve" => "CVGSpecial",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "13" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "CVGSpecial",
      ],
      "15" => [
        "Type" => "King",
        "Reserve" => "CVGSpecial",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "17" => [
        "Type" => "King",
        "Reserve" => "CVGSpecial",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "CVGSpecial",
      ],
      "19" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "CVGSpecial",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "CVGSpecial",
      ],
    ],
    "10" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "03" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "05" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "07" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "09" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "10" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "11" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "13" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "15" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "17" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "19" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
    ],
    "11" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "03" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "05" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "07" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "09" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "10" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "11" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "13" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "15" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "17" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "19" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
    ],
    "12" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "03" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "05" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "07" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "09" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "10" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "11" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "13" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "15" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "17" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "19" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
    ],
    "14" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "03" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "05" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "07" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "09" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "10" => [
        "Type" => "Double",
        "Reserve" => "Pocket",
      ],
      "11" => [
        "Type" => "King",
        "Reserve" => "Pocket",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "Pocket",
      ],
      "13" => [
        "Type" => "King",
        "Reserve" => "Pocket",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "Pocket",
      ],
      "15" => [
        "Type" => "King",
        "Reserve" => "Pocket",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "Pocket",
      ],
      "17" => [
        "Type" => "King",
        "Reserve" => "Pocket",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "Pocket",
      ],
      "19" => [
        "Type" => "King",
        "Reserve" => "Pocket",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "InvParticipant",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
    ],
    "15" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "03" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "05" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "07" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "09" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "10" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "11" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "13" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "15" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "17" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "19" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
    ],
    "16" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "03" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "05" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "06" => [
        "Type" => "Suite",
        "Reserve" => "IWBlock",
      ],
      "07" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "09" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "10" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "11" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "13" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "15" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "17" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "19" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
    ],
    "17" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "03" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "04" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "05" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "06" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "07" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "08" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "09" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "10" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "11" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "13" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "14" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "15" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "16" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "17" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "18" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "19" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "20" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
    ],
    "18" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "02" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "03" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "04" => [
        "Type" => "King",
        "Reserve" => "Board",
      ],
      "05" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "06" => [
        "Type" => "Suite",
        "Reserve" => "Board",
      ],
      "07" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "09" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "10" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "11" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "12" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "13" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "14" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "15" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "16" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "17" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "18" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "19" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "20" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "22" => [
        "Type" => "King",
        "Reserve" => "",
      ],
    ],
    "19" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "02" => [
        "Type" => "Double",
        "Reserve" => "",
      ],
      "03" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "04" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "05" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "06" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "07" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "08" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "09" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "10" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "11" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "12" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "13" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "14" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "15" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "16" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "17" => [
        "Type" => "King",
        "Reserve" => "Pocket",
      ],
      "18" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "19" => [
        "Type" => "King",
        "Reserve" => "Pocket",
      ],
      "20" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "InvParticipant",
      ],
    ],
    "20" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "02" => [
        "Type" => "Suite",
        "Reserve" => "Board",
      ],
      "03" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "05" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "06" => [
        "Type" => "Suite",
        "Reserve" => "Board",
      ],
      "07" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "09" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "10" => [
        "Type" => "HC",
        "Reserve" => "ADA",
      ],
      "11" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "12" => [
        "Type" => "Double",
        "Reserve" => "InvParticipant",
      ],
      "13" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "14" => [
        "Type" => "Suite",
        "Reserve" => "CVGSpecial",
      ],
      "15" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "17" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "19" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "20" => [
        "Type" => "Suite",
        "Reserve" => "CVGSpecial",
      ],
      "22" => [
        "Type" => "Double",
        "Reserve" => "InvParticipant",
      ],
    ],
    "21" => [
      "01" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "02" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "03" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "04" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "05" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "06" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "07" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "08" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "09" => [
        "Type" => "King",
        "Reserve" => "",
      ],
      "10" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "11" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "12" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "13" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "14" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "15" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "16" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "17" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "18" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "19" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "20" => [
        "Type" => "King",
        "Reserve" => "InvParticipant",
      ],
      "22" => [
        "Type" => "King",
        "Reserve" => "Department",
      ],
    ],
  ],
];

function sendChangeToHotel($room) {
/*  Pending Function - not tested
  // send add update to the hotel
  $assignedRoomFieldId = array_search('Room Assigned', $_SESSION['definedFields']);
  $checkInFieldId = array_search('Check In', $_SESSION['definedFields']);
  $checkOutFieldId = array_search('Check Out', $_SESSION['definedFields']);
  $other1FieldId = array_search('Other In Room 1', $_SESSION['definedFields']);
  $other2FieldId = array_search('Other In Room 2', $_SESSION['definedFields']);
  $other3FieldId = array_search('Other In Room 3', $_SESSION['definedFields']);

  $search = [ 
    'method' => 'account/listAccounts', 
    'criteria' => [
      [$assignedRoomFieldId, 'CONTAIN', $room],
    ],
    'columns' => [
      'standardFields' => ['Account ID', 'First Name', 'Last Name', 'Phone 1', 'Email 1'],
      'customFields' => [$checkInFieldId, $checkOutFieldId, $other1FieldId, $other2FieldId, $other3FieldId],
    ],
    'page' => [
      'currentPage' => 1,
      'pageSize' => 200,
      'sortColumn' => 'Account ID',
      'sortDirection' => 'ASC',
    ],
  ];
  $result = $GLOBALS['Neon']->search($search);

  if ( isset( $result['operationResult'] ) && $result['operationResult'] == 'SUCCESS' ) {
    $roomPrefix = explode("-", $room);
    foreach($AllocHotels as $hkey => $hotel) {
      if($roomPrefix[0] == $hotel['Prefix']) {
        $to = $AllocHotels[$hkey]['Email'];
        $contact = $AllocHotels[$hkey]['Contact'];
      }
    }
    $subject = "New room assignment for " . $room;
    $headers = 'From: allocations@convergence-con.org' . "\r\n";
    $headers .= 'Reply-To: allocations@convergence-con.org' . "\r\n";
//    $headers .= 'Cc: allocations@convergence-con.org';
    $message = "Dear " . $contact . ",\n";
    $message .= "Please assign room " . $room . " to " . $firstName . " " . $lastName . ".\n";
    $message .= "Check In: " . $checkIn . ", Check Out: " . $checkOut . "\n";
    $message .= "Others in room: " . $other1 . ", " . $other2 . ", " . $other3 . "\n\n";
    $message .= 'ARR_DATE,ARR_TIME,DEP_DATE,TITLE,FIRST_NAME,LAST_NAME,NUM_ROOMS,ROOM_TYPE,ROOM_RATE,DEPOSIT_AMT,NON_SMOKE,SPREQ_1,SPREQ_2,SPREQ_3,SPREQ_4,NUM_ADULTS,NUM_CHILD,HOME_PHONE,BUS_PHONE,FAX_NUM,EMAIL_ADD,COMPANY,ADDRESS,ADDRESS2,CITY,STATE,ZIP,COUNTRY,HOTEL_COMMENTS,RES_COMMENTS,CC_NAME,CC_NUMBER,CC_EXPIRE,TITLE2,FIRST_NAME2,LAST_NAME2,TITLE3,FIRST_NAME3,LAST_NAME3,TITLE4,FIRST_NAME4,LAST_NAME4,HHONORS_NUM,SUB_GROUP_NUM,TA_IATA_NUM,TP_TRACKING_NUM' . "\n";
    $message .= $checkInDate . ",15:00," . $checkOutDate . ",," . $firstName . "," . $lastName . ",1,,,,,,,,,," . $phone . ",,," . $email  . ",," . $addr1 . "," . $addr2 . "," $city . "," . $state . "," . $zip . "," . $country . "," . $room . ",Do Not Move - " . $accountId . ",,,,,," . $other1 . ",,," . $other2 . ",,," . $other3 . "\n\n";
    mail($to, $subject, $message, $headers);
  } else {
    sendError("Room Search Fail", $result);
  }
*/
}

function updateRoomsInfo($page) {
  $assignedRoomFieldId   = array_search('Room Assigned', $_SESSION['definedFields']);
  $overrideCatFieldId    = array_search('Hotel Override Category', $_SESSION['definedFields']);
  $overrideRoomFieldId   = array_search('Hotel Override', $_SESSION['definedFields']);
  $lotteryStatusFieldId  = array_search('Lottery Status', $_SESSION['definedFields']);
  $qualifierFieldId      = array_search('Hotel Qualifier', $_SESSION['definedFields']);
  $roomPreferenceFieldId = array_search('Bed Preference', $_SESSION['definedFields']);
  $checkInFieldId        = array_search('Check In', $_SESSION['definedFields']);
  $checkOutFieldId       = array_search('Check Out', $_SESSION['definedFields']);
  $other1FieldId         = array_search('Other In Room 1', $_SESSION['definedFields']);
  $other2FieldId         = array_search('Other In Room 2', $_SESSION['definedFields']);
  $other3FieldId         = array_search('Other In Room 3', $_SESSION['definedFields']);

  $search = [
    'method' => 'account/listAccounts', 
    'criteria' => [
      [$assignedRoomFieldId, 'NOT_BLANK', ''],
    ],
    'columns' => [
      'standardFields' => [
        'Account ID',
        'First Name',
        'Last Name',
        'Phone 1 Full Number (F)',
        'Email 1'
      ],
      'customFields' => [
        $assignedRoomFieldId,
        $overrideCatFieldId,
        $overrideRoomFieldId,
        $lotteryStatusFieldId,
        $qualifierFieldId,
        $roomPreferenceFieldId,
        $checkInFieldId,
        $checkOutFieldId,
        $other1FieldId,
        $other2FieldId,
        $other3FieldId,
      ],
    ],
    'page' => [
      'currentPage' => $page,
      'pageSize' => 200,
      'sortColumn' => 'Account ID',
      'sortDirection' => 'ASC',
    ],
  ];
  $result = $GLOBALS['Neon']->search($search);

  if ( isset( $result['operationResult'] ) && $result['operationResult'] == 'SUCCESS' ) {
    $return['pages'] = $result['page']['totalPage'];

    foreach($result['searchResults'] as $val) {
      $rooms = explode('|', $val['Room Assigned']);
      unset($val['Room Assigned']); // Don't keep the raw room info in alloc, if changes happen, it would be wrong until refresh
      foreach($rooms as $room) {
        $return['list'][$room] = $val;
      }
      unset($rooms);
    }
  } else {
    sendError("Could not retrieve RoomList " . __FILE__, $result);
    $return = FALSE;
  }
  return $return;
}

function populateAllocInfo() {
  $fullRoomList=[];
  $i=1;
  $runPage=1;
  while ( $i <= $runPage ) {
    $result = updateRoomsInfo($i);
    $tmp = array_merge_recursive($fullRoomList, $result['list']);
    $fullRoomList = $tmp;
    unset($tmp);
    $runPage = $result['pages'];
    $i++;
  }
  return $fullRoomList;
}

function totalAvailableRooms($hotel) {
  global $AllocRooms;
  foreach ($AllocRooms[$hotel] as $room) {
    if(empty($counts[$room['Type']])) {
      $counts[$room['Type']] = 1;
    } else {
      $counts[$room['Type']]++;
    }
    if(!empty($room['Reserve'])) {
      if(empty($counts[$room['Reserve']])) {
        $counts[$room['Reserve']] = 1;
      } else {
        $counts[$room['Reserve']]++;
      }
    }
  }
  $counts['Total'] = count($AllocRooms[$hotel]);
  return $counts;
}

?>
