INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID, FallbackID) VALUES (2, 'Activities', 2, 8);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID, FallbackID) VALUES (3, 'Administration', 3, 2);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID, FallbackID) VALUES (4, 'External Relations and Communications', 4, 3);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID, FallbackID) VALUES (5, 'Facilities', 5, 4);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID, FallbackID) VALUES (6, 'Hospitality', 6, 5);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID, FallbackID) VALUES (7, 'Productions', 7, 6);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID, FallbackID) VALUES (8, 'Systems', 8, 7);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (9, 'Committees', 9);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (10, 'Corporate Staff', 10);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (11, 'CFO Staff', 11);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (100, 'Accessibility and Inclusion', 4);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (101, 'Allocations', 5);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (102, 'Archives', 3);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (103, 'Artist Alley', 4);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (104, 'Art Show', 3);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (105, 'Book Swap', 2);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (107, 'Ceremonies', 7);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (108, 'Cinema Rex', 7);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (109, 'CoF2E2', 6);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (110, 'Connies Quantum Sandbox', 2);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (111, 'ConSuite', 6);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (112, 'Creative Services', 4);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (113, 'CVG-TV', 7);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (114, 'Dealers Room', 4);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (115, 'Decor', 5);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (116, 'Dock', 5);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (117, 'Exhibits', 2);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (118, 'Finance', 11);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (119, 'First Advisors', 6);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (120, 'Future Visioning', 9);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (121, 'Gaming', 2);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (122, 'Guest Search', 9);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (123, 'Guests of Honor', 3);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (124, 'Harmonic Convergence', 7);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (125, 'Hotel', 5);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (126, 'Invited Participants', 2);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (127, 'IT', 8);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (128, 'Logistics', 5);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (129, 'MainStage', 7);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (130, 'Masquerade', 7);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (131, 'Meeting Childcare', 5);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (132, 'Member Advocates', 9);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (133, 'Merchandise', 3);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (134, 'Nerf Herders', 5);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (135, 'Operations', 6);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (136, 'Partner Management', 3);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (137, 'Partner Search', 9);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (138, 'Photography', 4);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (139, 'President', 10);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (140, 'Programming', 2);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (141, 'Publications', 4);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (142, 'Registration', 3);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (143, 'Event Orders', 5);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (144, 'Room Parties', 6);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (145, 'Secretary', 10);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (146, 'Smokers Paradise', 6);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (147, 'Social Media', 4);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (148, 'Space Lounge', 6);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (149, 'Teen Room', 2);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (150, 'Theater Nippon', 7);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (151, 'Transportation', 5);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (152, 'Treasurer', 10);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (153, 'Vice-President', 10);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (154, 'Video', 7);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (155, 'Volunteer Den', 6);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (156, 'Volunteers', 3);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (157, 'Webteam', 4);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (158, 'Youth Programming Advisory', 9);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (159, 'Transition Team', 9);
INSERT INTO Departments (DepartmentID, Name, ParentDepartmentID) VALUES (160, 'Spoken Word', 2);
