<script src="modules/artshow/artist/sitesupport/artist.js"></script>
<script src="sitesupport/barcode/quagga.min.js"></script>
<script src="sitesupport/barcode/barcode.js"></script>
<script src="sitesupport/profile.js"></script>
<script src="sitesupport/common.js"></script>
<script src="sitesupport/confirmbox.js"></script>
<script src="sitesupport/lookupuser.js"></script>
<link rel="stylesheet" type="text/css" href="sitesupport/barcode/barcode.css" />
