<div id="page" class="UI-container">
    <div id="main_content" class="UI-maincontent">
       <div class="UI-event-sectionbar">
            <span>Registration Admin</span>
       </div>
        <div class="UI-container UI-padding">
            <div class="UI-border UI-padding UI-margin UI-container">
                <div id="settings" class="UI-table-all">
                    <div class="UI-table-row">
                        <div class="UI-table-cell UI-center">
                            <span class="UI-center">Nothing to Set...</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
