<?php
?>
<script src="sitesupport/sidebar.js"></script>
<script src="sitesupport/barcode/quagga.min.js"></script>
<script src="sitesupport/barcode/barcode.js"></script>
<script src="sitesupport/confirmbox.js"></script>
<script src="modules/registration/sitesupport/registration.js"></script>
<link rel="stylesheet" type="text/css" href="sitesupport/barcode/barcode.css" />
<script type="module" src="modules/registration/sitesupport/vue.js"></script>
<?php
require_once $BASEDIR.'/console/console.inc';
console_head();
