Hi <?=$name?>,

You recently requested to create your password for your <?=$con?> Login. Click the link below to Create it.

<a href="<?=$url?>&email=<?=$email?>&authorization=<?=$code?>">Create Password</a>

If you didn't request to create a password, please ignore this email. This link to create a password is only valid until <?=$expire?>.
Thanks,
<?=$con?> Support Team

If you are having trouble clicking on the create password button, please copy and paste the following URL into your web Browser.

<?=$url?>&email=<?=$email?>&authorization=<?=$code?>
