<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>
<title>Password Creation</title>
</head>
<body>
<div>
<p>Hi <?=$name?>,</p>
<p>You recently requested to create your password for your <?=$con?> Login. Click the link below to Create it.</p>
<p><a href="<?=$url?>&email=<?=$email?>&authorization=<?=$code?>">Create Password</a></p>
<p>If you didn't request to create a password, please ignore this email. This link to create a password is only valid until <?=$expire?>.</p>
<p>Thanks,</p>
<p><?=$con?> Support Team</p>
<p>If you are having trouble clicking on the create password button, please copy and paste the following URL into your web Browser.</p>
<p><?=$url?>&email=<?=$email?>&authorization=<?=$code?></p>
</div>
</body>
</html>
