<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>
<title>Password Reset</title>
</head>
<body>
<div>
<p>Hi <?=$name?>,</p>
<p>You recently requested to reset your password for your <?=$con?> Login. Click the link below to reset it.</p>
<p><a href="<?=$url?>&email=<?=$email?>&authorization=<?=$code?>">RESET BUTTON</a></p>
<p>If you didn't request a password reset, please ignore this email. This password reset is only valid until <?=$expire?>.</p>
<p>Thanks,</p>
<p><?=$con?> Support Team</p>
<p>If you are having trouble clicking on the reset password link, please copy and paste the following URL into your web Browser.</p>
<p><?=$url?>&email=<?=$email?>&authorization=<?=$code?></p>
</div>
</body>
</html>
