Hi <?=$name?>,

You recently requested to reset your password for your <?=$con?> Login. Click the link below to reset it.

<a href="<?=$url?>&email=<?=$email?>&authorization=<?=$code?>">RESET BUTTON</a>

If you didn't request a password reset, please ignore this email. This password reset is only valid until <?=$expire?>.

Thanks,
<?=$con?> Support Team

If you are having trouble clicking on the reset password link, please copy and paste the following URL into your web Browser.

<?=$url?>&email=<?=$email?>&authorization=<?=$code?>
