<script src="sitesupport/sidebar.js"></script>
<script type="text/javascript" src="modules/emailer/sitesupport/emailer.js"></script>
<script type="text/javascript" src="modules/emailer/sitesupport/emailer2.js.php"></script>
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<script src="sitesupport/confirmbox.js"></script>
