<p></p>
<div class="w3-bar">
  <div class="w3-dropdown-hover">
    <button class="w3-bar-item w3-button w3-tiny"><img src="images/dualXicon.png" style="height: 2em; width: 2em;" alt="Dual X Icon - Con-In-A-Box"> Information</button>
    <div class="w3-dropdown-content">
      <div class="w3-panel w3-leftbar w3-sand">
        Con-In-A-Box&trade;
<?php
echo ' - In use by: ' . $CONHOST . "\n";
echo ' - Included Modules: ' . $MODULENAME . ' v-' . $VERSION . "\n";
?>
      </div>

      <div class="w3-panel w3-leftbar w3-small w3-lime">
        All parts of Con-In-A-Box&trade;, including but not limited to the Dual-X icon, CON-In-A-Box&trade; logo, name CON-In-A-Box&trade;, scripts, programs, coding, styles, data models, CGI, HTML, custom PHP, structure, feeds, or methods, except where otherwise protected (exceptions include but not limited to the Neon-php library maintained by z2systems, the Speller Pages Project from Sourceforge.net protected under the GNU Public License, or the PHP-Fortune script from Henrik Aasted Sorensen) are:
        <div class="w3-container w3-center w3-large">
          &copy; Copyright 2005-2017 Thomas S. Keeley
        </div>
      </div>

      <div class="w3-panel w3-leftbar w3-small w3-khaki">
        Licensed under the Apache License, Version 2.0 (the "License"); you may not use any part of Con-In-A-Box&trade; except in compliance with the License. You may obtain a copy of the License at

        <div class="w3-container">
          <a href="http://www.apache.org/licenses/LICENSE-2.0">http://www.apache.org/licenses/LICENSE-2.0</a>
        </div>
        
        Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
      </div>
      
      <div class="w3-panel w3-leftbar w3-orange">
        Actual data information, entries, and tracking are Private and Confidential and may not be used in anyway the is contrary to the policies of the group, legal entity, or organization using Con-In-A-Box&trade;.  By accessing this site, you agree and consent to same said policies and acknowledge any legal responsibility therein contained.
      </div>
    </div>
  </div>
</div>
