<p></p>
  <div class="w3-bar">
    <div class="w3-dropdown-hover">
      <button class="w3-bar-item w3-button w3-tiny">&copy; Information</button>
      <div class="w3-dropdown-content w3-small">
        <p>All parts of Con-In-A-Box<SMALL><SUP>TM</SUP></SMALL>, including but not limited to the Dual-X icon, CON-In-A-Box<SMALL><SUP>TM</SUP></SMALL> logo, name CON-In-A-Box<SMALL><SUP>TM</SUP></SMALL>, scripts, programs, coding, styles, data models, CGI, HTML, custom PHP, structure, feeds, or methods, except where otherwise protected (exceptions include but not limited to the Neon-php library maintained by z2systems, the Speller Pages Project from Sourceforge.net protected under the GNU Public License, or the PHP-Fortune script from Henrik Aasted Sorensen) are:</p>

        <p>&copy; Copyright 2005-2017 Thomas S. Keeley.</p>

        <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use any part of Con-In-A-Box<SMALL><SUP>TM</SUP></SMALL> except in compliance with the License. You may obtain a copy of the License at <a href="http://www.apache.org/licenses/LICENSE-2.0">http://www.apache.org/licenses/LICENSE-2.0</a> Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.<p>

        <p>Actual data information, entries, and tracking are Private and Confidential and may not be used in anyway the is contrary to the policies of the group, legal entity, or organization using Con-In-A-Box<SMALL><SUP>TM</SUP></SMALL>.  By accessing this site, you are consenting to same said policies and acknowledge any legal responsibility therein contained.</p>
      </div>
    </div>
  </div>
