<div class="Disclaimer"> <!-- Add Standard Disclaimer -->
<h6>
All parts of Con-In-A-Box<SMALL><SUP>TM</SUP></SMALL>, including but not limited to scripts, programs, coding, styles, data models, CGI, HTML, custom PHP, structure, feeds, or methods, except where otherwise protected (exceptions include but not limited to the Speller Pages Project from Sourceforge.net protected under the GNU Public License or the PHP-Fortune script from Henrik Aasted Sorensen) are:
<br>
&copy;Copyright 2005 - 2016 by Thomas S. Keeley.  ALL RIGHTS RESERVED.  No warranty, expressed or implied, is made to the functionality or use of CON-In-A-Box<SMALL><SUP>TM</SUP></SMALL> by Thomas Keeley or any subsidiary there of.  CON-In-A-Box<SMALL><SUP>TM</SUP></SMALL> is a subscription based package and may not be used, copied, distributed, edited, or otherwise accessed without the express written consent of Thomas S. Keeley.
<br>
The Dual-X icon, CON-In-A-Box<SMALL><SUP>TM</SUP></SMALL> logo, and name CON-In-A-Box<SMALL><SUP>TM</SUP></SMALL> are trademarks of CON-In-A-Box<SMALL><SUP>TM</SUP></SMALL>, maintained and right-reserved by Thomas S. Keeley.
<br>
Actual data information, entries, and tracking are Private and Confidential and may not be used in anyway the is contrary to the policies of the convention using Con-In-A-Box<SMALL><SUP>TM</SUP></SMALL>.  By accessing this site, you are consenting to same said policies and acknowledge any legal responsibility therein contained.
</h6>
</div> <!-- Close Standard Disclaimer -->
