<!DOCTYPE html>
<html>
<head>
<title><?php echo $CONSITENAME; ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/sitesupport/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="icon" href="images/favicon.png">
<link rel="shortcut icon" href="images/favicon.png">

