<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>
<title><?php echo $CONSITENAME; ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="images/favicon.png">
<link rel="shortcut icon" href="images/favicon.png">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/all.css">
<script defer src="https://use.fontawesome.com/releases/v5.11.2/js/all.js"></script>
