<script src="sitesupport/sidebar.js"></script>
<script src="sitesupport/barcode/quagga.min.js"></script>
<script src="sitesupport/barcode/barcode.js"></script>
<script src="sitesupport/d3.v5.min.js"></script>
<script src="sitesupport/donut.js"></script>
<link rel="stylesheet" type="text/css" href="sitesupport/barcode/barcode.css" />
<link rel="stylesheet" type="text/css" href="theme.css">
<link rel="stylesheet" href="https://unpkg.com/vuetify@3.4.2/dist/vuetify.css">
<link href="https://unpkg.com/@mdi/font@5.x/css/materialdesignicons.min.css" rel="stylesheet">
<script type="module" src="modules/concom/sitesupport/division-parser.js"></script>
<script type="module" src="modules/concom/sitesupport/concom-list.js"></script>
