<script src="modules/concom/sitesupport/concom.js"></script>
<script src="sitesupport/barcode/quagga.min.js"></script>
<script src="sitesupport/barcode/barcode.js"></script>
<script src="sitesupport/common.js"></script>
<script src="sitesupport/lookupuser.js"></script>
<link rel="stylesheet" type="text/css" href="sitesupport/barcode/barcode.css" />
<link rel="stylesheet" type="text/css" href="theme.css">
