<script src="sitesupport/confirmbox.js" type="text/javascript"> </script>
<script src="sitesupport/barcode/quagga.min.js" type="text/javascript"> </script>
<script src="sitesupport/barcode/barcode.js" type="text/javascript"> </script>
<script src="sitesupport/common.js" type="text/javascript"> </script>
<script src="sitesupport/confirmbox.js" type="text/javascript"> </script>
<script src="sitesupport/sidebar.js" type="text/javascript"> </script>
<link rel="stylesheet" type="text/css" href= "sitesupport/barcode/barcode.css">
<script type="module" src="modules/artshow/sales/vue/sales.js"></script>
