<script src="modules/artshow/sitesupport/common.js" type="text/javascript">
</script>
<script src="modules/artshow/sitesupport/artTable.js" type=
"text/javascript"> </script>
<script src="modules/artshow/sitesupport/hungArtTable.js" type=
"text/javascript"> </script>
<script src="modules/artshow/sitesupport/printArtTable.js" type=
"text/javascript"> </script>
<script src="modules/artshow/art/sitesupport/art.js" type=
"text/javascript"> </script>
<script src="modules/artshow/sitesupport/piece.js" type="text/javascript">
</script>
<script src="modules/artshow/sitesupport/print.js" type="text/javascript">
</script>
<script src="modules/artshow/sitesupport/hungArtEntryTable.js" type=
"text/javascript"> </script>
<script src="modules/artshow/sitesupport/printArtEntryTable.js" type=
"text/javascript"> </script>
<script src="sitesupport/barcode/quagga.min.js" type="text/javascript"> </script>
<script src="sitesupport/barcode/barcode.js" type="text/javascript"> </script>
<script src="sitesupport/common.js" type="text/javascript"> </script>
<script src="sitesupport/confirmbox.js" type="text/javascript"> </script>
<script src="sitesupport/lookupuser.js" type="text/javascript"> </script>
<script src="sitesupport/profile.js" type="text/javascript"> </script>
<script src="sitesupport/sidebar.js" type="text/javascript"> </script>
<link rel="stylesheet" type="text/css" href= "sitesupport/barcode/barcode.css">
