<?php
?>
<script src="sitesupport/sidebar.js"></script>
<script src="sitesupport/barcode/quagga.min.js"></script>
<script src="sitesupport/barcode/barcode.js"></script>
<script src="sitesupport/confirmbox.js"></script>
<script src="modules/volunteers/sitesupport/volunteers.js"></script>
<script src="sitesupport/confirmbox.js"></script>
<link rel="stylesheet" type="text/css" href="sitesupport/barcode/barcode.css" />
<script type="module" src="modules/volunteers/admin/vue/vue.js"></script>
<style>
.hiddenrow {
    display:none;
};

</style>
<?php
require_once $BASEDIR.'/console/console.inc';
console_head();
