<div id="dynamic_content" class="main_screen">
<?php require($PAGESDIR . '/base/leftnav.inc'); ?>
<div id="main_content" style="text-align:center;">
<h2>To update your profile information:</h2>
<img src="images/Neon-MainScreen.png" alt="Main login page" style="border:5px solid black;">
<p>Click the 'Update' button below which will take you to the Neon Login page (above).  Login using the same credentials you used to signin here.</p>
<p>&nbsp;</p>

<img src="images/Neon-Menu.png" alt="Drop down menu" style="border:5px solid black;">
<p>After logging in, you will be at the Constituent Login page.<br />
Use the drop down menu to select 'Update my profile' which will give you a form to fill in and correct any of your personal information.</p>
<p>&nbsp;</p>

<p style="text-align:center;"><a href="https://www.z2systems.com/np/clients/ce/login.jsp"><img src="images/update_button.png" alt="Update My Profile"></a><br />
Click here to get started!</p>

</div><!--close main_content div-->
