<?php require($PAGESDIR . '/base/leftnav.inc'); ?>
<div id="main_content" class="w3-cell w3-cell-top w3-mobile">
<h2>To check to see if you are registered for CONvergence:</h2>

<img src="images/Neon-MainScreen.png" alt="Main login page" style="border:5px solid black;">
<p>Click the 'Update' button below which will take you to the Neon Login page (above).  Login using the same credentials you used to signin here.</p>

<p>&nbsp;</p>

<img src="images/Neon-Menu.png" alt="Drop down menu" style="border:5px solid black;">
<p>After logging in, you will be at the Constituent Login page.<br />
Use the drop down menu to select 'My Registered Events'</p>

<p>&nbsp;</p>

<img src="images/Neon-EventsRegistered.png" alt="Registered Events" style="border:5px solid black;">
<p>This is a list of all events that you have registered for in Neon.<br />
If you are registered for this year, the top listing will show the current convention year</p>

<p>&nbsp;</p>

<p>
<a href="https://www.z2systems.com/np/clients/ce/login.jsp" class="w3-btn w3-round-xlarge w3-green">Click here to get started!</a>
</p>

</div><!--close main_content div-->
