<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<script type="text/javascript">
</script>

<body>
<div id="page" class="UI-container">
    <div id="main_content" class="UI-maincontent">
        <div class="UI-event-sectionbar">
            <span>Art Show Piece Details</span>
        </div>

        <div id="headline_section" class=
        "UI-container UI-border UI-margin UI-padding UI-hide"></div>

        <art-piece ref=pce read-only> </art-piece>
    </div>
</div>
