#!/bin/bash

cwd=${PWD}

if [[ $cwd = *"tools"* ]]; then
  cd ..;
fi

if [ -z "$1" ]
    then
        find . -type f \( -iname "*.js" ! -iname "*.min.js" ! -path "*/sitesupport/speller/*" \)  -exec jscs --verbose --reporter inline {} \;
    else
        jscs --verbose --reporter inline $1;
fi;
