#!/bin/bash

cwd=${PWD}

if [[ $cwd = *"tools"* ]]; then
  cd ..;
fi

if [ -z "$1" ]
    then
        phpcs --report=summary --colors
    else
        if [ "$1" == "--fix" ]
        then
            phpcbf --ignore=*.js $2;
        else
            phpcs --colors $1;
        fi
fi;
