#!/bin/bash

cwd=${PWD}

if [[ $cwd = *"tools"* ]]; then
  cd ..;
fi

if [ -z "$1" ]
    then
        phpcs --standard=./data/phpcs_ruleset.xml --report=summary --colors --ignore=sitesupport,neon,data,library,*.js *;
    else
        if [ "$1" == "--fix" ]
        then
            phpcbf --standard=./data/phpcs_ruleset.xml --ignore=*.js $2;
        else
            phpcs --standard=./data/phpcs_ruleset.xml --colors --ignore=sitesupport,neon,data,library,*.js $1;
        fi
fi;
